# Generated by Django 4.2.10 on 2025-12-11 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_jsonld', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
